# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - 0.6

matrix:
  allow_failures: 
    - os: osx # OSX does not seem to agree with TB on a VM

notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("LaTeXTools"); Pkg.test("LaTeXTools"; coverage=true)'
